# Generated by Django 5.1.3 on 2025-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
